import { Albums } from "./albums";

export interface Song {
    id: number;
    albumId: number;
    title: string;
    image: string;
    artists: string[];
    album: string;
    duration: string;
  }

export const songs: Song[] = [
    
  {
    id: 1,
    albumId: 1,
    title: "Moonlit Walk",
    image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
    artists: Albums[0].artists,
    album: "Chill Lo-Fi Music",
    duration: "3:12"
  },

  {
    id: 2,
    albumId: 1,
    title: "Coffee Daze",
    image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
    artists: Albums[0].artists,
    album: "Chill Lo-Fi Music",
    duration: "4:07"
  },

  {
    id: 3,
    albumId: 1,
    title: "Skyline Serenade",
    image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
    artists: Albums[0].artists,
    album: "Chill Lo-Fi Music",
    duration: "3:50"
  },

  {
    id: 4,
    albumId: 1,
    title: "Urban Echoes",
    image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
    artists: Albums[0].artists,
    album: "Chill Lo-Fi Music",
    duration: "3:30"
  },

  {
    id: 5,
    albumId: 1,
    title: "Night's End",
    image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
    artists: Albums[0].artists,
    album: "Chill Lo-Fi Music",
    duration: "4:20"
  },

  //Album with songs 2

  {
    id: 1,
    albumId: 2,
    title: "Silent Rain",
    image: Albums[1].cover,
    artists: Albums[1].artists,
    album: "Midnight Tales",
    duration: "3:40"
  },

  {
    id: 2,
    albumId: 2,
    title: "Lost Pages",
    image: Albums[1].cover,
    artists: Albums[1].artists,
    album: "Midnight Tales",
    duration: "3:20"
  },

  {
    id: 3,
    albumId: 2,
    title: "Midnight Tales",
    image: Albums[1].cover,
    artists: Albums[1].artists,
    album: "Midnight Tales",
    duration: "3:50"
  },

  {
    id: 4,
    albumId: 2,
    title: "City Lights",
    image: Albums[1].cover,
    artists: Albums[1].artists,
    album: "Midnight Tales",
    duration: "3:30"
  },

  {
    id: 5,
    albumId: 2,
    title: "Night Drive",
    image: Albums[1].cover,
    artists: Albums[1].artists,
    album: "Midnight Tales",
    duration: "4:20"
  },

  //Album withs songs 3

  {
    id: 1,
    albumId: 3,
    title: "Lunar",
    image: Albums[2].cover,
    artists: Albums[2].artists,
    album: "Study Session",
    duration: "3:40"
  },

  {
    id: 2,
    albumId: 3,
    title: "Go go go!",
    image: Albums[2].cover,
    artists: Albums[2].artists,
    album: "Study Session",
    duration: "3:20"
  },

  {
    id: 3,
    albumId: 3,
    title: "Keep focus!",
    image: Albums[2].cover,
    artists: Albums[2].artists,
    album: "Study Session",
    duration: "2:40"
  },

  {
    id: 4,
    albumId: 3,
    title: "JavaScript is the way",
    image: Albums[2].cover,
    artists: Albums[2].artists,
    album: "Study Session",
    duration: "3:10"
  },

  {
    id: 5,
    albumId: 3,
    title: "No more TypeScript for me",
    image: Albums[2].cover,
    artists: Albums[2].artists,
    album: "Study Session",
    duration: "2:10"
  },

// Album with songs 4

  {
    id: 1,
    albumId: 4,
    title: "Lunar",
    image: "https://f4.bcbits.com/img/a1962013209_16.jpg",
    artists: ["Tenno"],
    album: "Study Session",
    duration: "3:40"
  },

  {
    id: 2,
    albumId: 4,
    title: "Go go go!",
    image: "https://f4.bcbits.com/img/a1962013209_16.jpg",
    artists: ["Tenno"],
    album: "Study Session",
    duration: "3:20"
  },

  {
    id: 3,
    albumId: 4,
    title: "Keep focus!",
    image: "https://f4.bcbits.com/img/a1962013209_16.jpg",
    artists: ["Tenno"],
    album: "Study Session",
    duration: "2:40"
  },

  {
    id: 4,
    albumId: 4,
    title: "JavaScript is the way",
    image: "https://f4.bcbits.com/img/a1962013209_16.jpg",
    artists: ["Tenno"],
    album: "Study Session",
    duration: "3:10"
  },

  {
    id: 5,
    albumId: 4,
    title: "No more TypeScript for me",
    image: "https://f4.bcbits.com/img/a1962013209_16.jpg",
    artists: ["Tenno"],
    album: "Study Session",
    duration: "2:10"
  },

  //Album with songs 5

  {
    id: 1,
    albumId: 5,
    title: "Moonlit Walk",
    image: "https://f4.bcbits.com/img/a2793859494_16.jpg",
    artists: ["LoFi Dreamer"],
    album: "Chill Lo-Fi Music",
    duration: "3:12"
  },

  {
    id: 2,
    albumId: 5,
    title: "Coffee Daze",
    image: "https://f4.bcbits.com/img/a2793859494_16.jpg",
    artists: ["LoFi Dreamer"],
    album: "Chill Lo-Fi Music",
    duration: "4:07"
  },

  {
    id: 3,
    albumId: 5,
    title: "Skyline Serenade",
    image: "https://f4.bcbits.com/img/a2793859494_16.jpg",
    artists: ["LoFi Dreamer"],
    album: "Chill Lo-Fi Music",
    duration: "3:50"
  },

  {
    id: 4,
    albumId: 5,
    title: "Urban Echoes",
    image: "https://f4.bcbits.com/img/a2793859494_16.jpg",
    artists: ["LoFi Dreamer"],
    album: "Chill Lo-Fi Music",
    duration: "3:30"
  },

  {
    id: 5,
    albumId: 5,
    title: "Night's End",
    image: "https://f4.bcbits.com/img/a2793859494_16.jpg",
    artists: ["LoFi Dreamer"],
    album: "Chill Lo-Fi Music",
    duration: "4:20"
  },

  //Album with songs Junior H

  {
    id: 1,
    albumId: 6,
    title: "A TU NOMBRE",
    image: Albums[5].cover,
    artists: Albums[5].artists,
    album: "$AD BOYZ 4 LIFE II",
    duration: "3:12"
  },

  {
    id: 2,
    albumId: 6,
    title: "EN LA PEDA",
    image: Albums[5].cover,
    artists: Albums[5].artists,
    album: "$AD BOYZ 4 LIFE II",
    duration: "4:07"
  },

  {
    id: 3,
    albumId: 6,
    title: "ENTRE NOSOTROS",
    image: Albums[5].cover,
    artists: Albums[5].artists,
    album: "$AD BOYZ 4 LIFE II",
    duration: "3:50"
  },

  {
    id: 4,
    albumId: 6,
    title: "PARIS",
    image: Albums[5].cover,
    artists: Albums[5].artists,
    album: "$AD BOYZ 4 LIFE II",
    duration: "3:30"
  },

  {
    id: 5,
    albumId: 6,
    title: "EN LAS NOCHES",
    image: Albums[5].cover,
    artists: Albums[5].artists,
    album: "$AD BOYZ 4 LIFE II",
    duration: "4:20"
  },

  /*------Lover Taylor Swift -*/
  {
    id: 1,
    albumId: 13,
    title: 'I Forgot That You Existed',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '2:50',
  },
  {
    id: 2,
    albumId: 13,
    title: 'Cruel Summer',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '2:50',
  },
  {
    id: 3,
    albumId: 13,
    title: 'Lover ',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:41',
  },
  {
    id: 4,
    albumId: 13,
    title: 'The Man',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:10',
  },
  {
    id: 5,
    albumId: 13,
    title: 'The Archer',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:31',
  },
  {
    id: 6,
    albumId: 13,
    title: 'I Think He Knows',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '2:53',
  },
  {
    id: 7,
    albumId: 13,
    title: 'Miss Americana & The Heartbreak Prince',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:54',
  },
  {
    id: 8,
    albumId: 13,
    title: 'Paper Rings',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:42',
  },
  {
    id: 9,
    albumId: 13,
    title: 'Cornelia Street',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '4:47',
  },
  {
    id: 10,
    albumId: 13,
    title: 'Death By A Thousan Cuts',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:18',
  },
  {
    id: 11,
    albumId: 13,
    title: 'Londo Boy',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:10',
  },
  {
    id: 12,
    albumId: 13,
    title: 'Sonn You\'ll Get Better (feat. The Chicks)',
    image: Albums[12].cover,
    artists: ['Taylor Swift', 'The Chicks'],
    album: 'Lover',
    duration: '3:21',
  },
  {
    id: 13,
    albumId: 13,
    title: 'False God',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:20',
  },
  {
    id: 14,
    albumId: 13,
    title: 'You Need To Calm Down',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:51',
  },
  {
    id: 15,
    albumId: 13,
    title: 'Afterglow',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '3:43',
  },
  {
    id: 16,
    albumId: 13,
    title: 'ME! (feat. Brendon Urie of Panic At The Disco)',
    image: Albums[12].cover,
    artists: ['Taylor Swift', 'feat. Brendon Urie of Panic At The Disco'],
    album: 'Lover',
    duration: '3:13',
  },
  {
    id: 17,
    albumId: 13,
    title: 'It\'s Nice To Have A Friend',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '2:30',
  },
  {
    id: 18,
    albumId: 13,
    title: 'Daylight',
    image: Albums[12].cover,
    artists: ['Taylor Swift'],
    album: 'Lover',
    duration: '4:53',
  },
  /*---------Bad Bunny YHLQMDLG------------ */
  {
    id: 1,
    albumId: 14,
    title: 'Si Veo a Tu Mamá',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '2:50',
  },
  {
    id: 2,
    albumId: 14,
    title: 'La Difícil',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '2:43',
  },
  {
    id: 3,
    albumId: 14,
    title: 'Pero Ya No',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '2:40',
  },
  {
    id: 4,
    albumId: 14,
    title: 'La Santa',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Daddy Yankee'],
    album: 'YHLQMDLG',
    duration: '3:26',
  },
  {
    id: 5,
    albumId: 14,
    title: 'Yo Perreo Sola',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '3:31',
  },
  {
    id: 6,
    albumId: 14,
    title: 'Bichiyal',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Yaviah'],
    album: 'YHLQMDLG',
    duration: '3:16',
  },
  {
    id: 7,
    albumId: 14,
    title: 'Soliá',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '2:39',
  },
  {
    id: 8,
    albumId: 14,
    title: 'La Zona',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '2:16',
  },
  {
    id: 9,
    albumId: 14,
    title: 'Que Malo',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Ñengo Flow'],
    album: 'YHLQMDLG',
    duration: '2:47',
  },
  {
    id: 10,
    albumId: 14,
    title: 'Vete',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '3:12',
  },
  {
    id: 11,
    albumId: 14,
    title: 'Ignorantes',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Sech'],
    album: 'YHLQMDLG',
    duration: '3:30',
  },
  {
    id: 12,
    albumId: 14,
    title: 'A Tu Merced',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '2:55',
  },
  {
    id: 13,
    albumId: 14,
    title: 'Una Vez',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Mora'],
    album: 'YHLQMDLG',
    duration: '3:52',
  },
  {
    id: 14,
    albumId: 14,
    title: 'Safaera',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Jowell & Randy', 'Ñengo Flow'],
    album: 'YHLQMDLG',
    duration: '4:55',
  },
  {
    id: 15,
    albumId: 14,
    title: '25/8',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '4:03',
  },
  {
    id: 16,
    albumId: 14,
    title: 'Está Cabrón Ser Yo',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Anuel AA'],
    album: 'YHLQMDLG',
    duration: '3:47',
  },
  {
    id: 17,
    albumId: 14,
    title: 'Puesto Pa\' Guerrial',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Myke Towers'],
    album: 'YHLQMDLG',
    duration: '3:10',
  },
  {
    id: 18,
    albumId: 14,
    title: 'P FKN R',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Kendo Kaponi', 'Arcángel'],
    album: 'YHLQMDLG',
    duration: '4:18',
  },
  {
    id: 19,
    albumId: 14,
    title: 'Hablamos Mañana',
    image: Albums[13].cover,
    artists: ['Bad Bunny', 'Duki', 'Pablo Chill-E'],
    album: 'YHLQMDLG',
    duration: '4:00',
  },
  {
    id: 20,
    albumId: 14,
    title: '<3',
    image: Albums[13].cover,
    artists: ['Bad Bunny'],
    album: 'YHLQMDLG',
    duration: '2:37',
  },
  /*---------Kygo ------------ */
  {
    id: 1,
    albumId: 15,
    title: 'Intro',
    image: Albums[14].cover,
    artists: ['Kygo'],
    album: 'Cloud Nine',
    duration: '2:08',
  },
  {
    id: 2,
    albumId: 15,
    title: 'Stole the Show',
    image: Albums[14].cover,
    artists: ['Kygo'],
    album: 'Cloud Nine',
    duration: '3:43',
  },
  {
    id: 3,
    albumId: 15,
    title: 'Fiction (feat. Tom Odell)',
    image: Albums[14].cover,
    artists: ['Kygo', 'Tom Odell'],
    album: 'Cloud Nine',
    duration: '4:03',
  },
  {
    id: 4,
    albumId: 15,
    title: 'Raging (feat. Kodaline)',
    image: Albums[14].cover,
    artists: ['Kygo', 'Kodaline'],
    album: 'Cloud Nine',
    duration: '3:44',
  },
  {
    id: 5,
    albumId: 15,
    title: 'Firestone',
    image: Albums[14].cover,
    artists: ['Kygo', 'Conrad Sewell'],
    album: 'Cloud Nine',
    duration: '4:31',
  },
  {
    id: 6,
    albumId: 15,
    title: 'Happy Birthday (feat. John Legend)',
    image: Albums[14].cover,
    artists: ['Kygo', 'John Legend'],
    album: 'Cloud Nine',
    duration: '4:10',
  },
  {
    id: 7,
    albumId: 15,
    title: 'I\'m in Love (feat. James Vincent McMorrow)',
    image: Albums[14].cover,
    artists: ['Kygo', 'James Vincent McMorrow'],
    album: 'Cloud Nine',
    duration: '3:32',
  },
  {
    id: 8,
    albumId: 15,
    title: 'Oasis (feat.Foxes)',
    image: Albums[14].cover,
    artists: ['Kygo', 'Foxes'],
    album: 'Cloud Nine',
    duration: '3:57',
  },
  {
    id: 9,
    albumId: 15,
    title: 'Not Alone (feat. RHODES)',
    image: Albums[14].cover,
    artists: ['Kygo','RHODES'],
    album: 'Cloud Nine',
    duration: '3:25',
  },
  {
    id: 10,
    albumId: 15,
    title: 'Serious(feat. Matt Corby)',
    image: Albums[14].cover,
    artists: ['Kygo', 'Matt Corby'],
    album: 'Cloud Nine',
    duration: '3:54',
  },
  {
    id: 11,
    albumId: 15,
    title: 'Stay (feat. Maty Noyes)',
    image: Albums[14].cover,
    artists: ['Kygo', 'Maty Noyes'],
    album: 'Cloud Nine',
    duration: '3:59',
  },
  {
    id: 12,
    albumId: 15,
    title: 'Nothing Left (feat. Will Heard)',
    image: Albums[14].cover,
    artists: ['Kygo', 'Will Heard'],
    album: 'Cloud Nine',
    duration: '3:56',
  },
  {
    id: 13,
    albumId: 15,
    title: 'Fragile',
    image: Albums[14].cover,
    artists: ['Kygo', 'Labrinth'],
    album: 'Cloud Nine',
    duration: '3:50',
  },
  {
    id: 14,
    albumId: 15,
    title: 'Carry Me (feat. Julia Michaels)',
    image: Albums[14].cover,
    artists: ['Kygo', 'Julia Michaels'],
    album: 'Cloud Nine',
    duration: '3:53',
  },
  {
    id: 15,
    albumId: 15,
    title: 'For What It\'s Worth (feat. Angus & Julia Stone)',
    image: Albums[14].cover,
    artists: ['Kygo','Angus & Julia Stone'],
    album: 'Cloud Nine',
    duration: '3:03',
  },
  /*-------Nata Montana--------- */
  {
    id: 1,
    albumId: 16,
    title: 'Díran de Mi',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'Tito Torbellino Jr'],
    album: 'Nata Montana',
    duration: '2:41',
  },
  {
    id: 2,
    albumId: 16,
    title: 'Mas Altas Que Bajadas',
    image: Albums[15].cover,
    artists: ['Natanael Cano'],
    album: 'Nata Montana',
    duration: '3:13',
  },
  {
    id: 3,
    albumId: 16,
    title: 'La Lokerona',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'HERNAN TREJO'],
    album: 'Nata Montana',
    duration: '3:14',
  },
  {
    id: 4,
    albumId: 16,
    title: 'Un Convoy',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'Amilkar Galaviz'],
    album: 'Nata Montana',
    duration: '2:38',
  },
  {
    id: 5,
    albumId: 16,
    title: 'YPancake',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'Peso Pluma'],
    album: 'Nata Montana',
    duration: '3:02',
  },
  {
    id: 6,
    albumId: 16,
    title: 'Viejo Lobo',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'Luis R Conriquez'],
    album: 'Nata Montana',
    duration: '2:50',
  },
  {
    id: 7,
    albumId: 16,
    title: 'AFS',
    image: Albums[15].cover,
    artists: ['Natanael Cano'],
    album: 'Nata Montana',
    duration: '4:02',
  },
  {
    id: 8,
    albumId: 16,
    title: 'Eres',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'Junior H'],
    album: 'Nata Montana',
    duration: '2:52',
  },
  {
    id: 9,
    albumId: 16,
    title: 'Mi Bello Angel',
    image: Albums[15].cover,
    artists: ['Natanael Cano'],
    album: 'Nata Montana',
    duration: '3:08',
  },
  {
    id: 10,
    albumId: 16,
    title: 'En Corto',
    image: Albums[15].cover,
    artists: ['Natanael Cano','Chino Pacas'],
    album: 'Nata Montana',
    duration: '3:02',
  },
  {
    id: 11,
    albumId: 16,
    title: 'AMG',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'Peso Pluma', 'Gabito Ballesteros'],
    album: 'Nata Montana',
    duration: '2:54',
  },
  {
    id: 12,
    albumId: 16,
    title: 'Como Es Arriba Es Abajo',
    image: Albums[15].cover,
    artists: ['Natanael Cano', 'Dan Sanchez'],
    album: 'Nata Montana',
    duration: '2:45',
  },
  {
    id: 13,
    albumId: 16,
    title: 'Pacas De Billetes',
    image: Albums[15].cover,
    artists: ['Natanael Cano'],
    album: 'Nata Montana',
    duration: '3:08',
  },
  {
    id: 14,
    albumId: 16,
    title: 'Dando y Dando',
    image: Albums[15].cover,
    artists: ['Natanael Cano'],
    album: 'Nata Montana',
    duration: '2:34',
  },
  {
    id: 15,
    albumId: 16,
    title: 'Ghini',
    image: Albums[15].cover,
    artists: ['Natanael Cano'],
    album: 'Nata Montana',
    duration: '2:36',
  },

  /*-------ICE BLUE--------- */
  {
    id: 1,
    albumId: 17,
    title: 'SEÑAL',
    image: Albums[16].cover,
    artists: ['OPYI', 'Birat Bitz'],
    album: 'ICE BLUE',
    duration: '3:02',
  },
  {
    id: 2,
    albumId: 17,
    title: 'NADA',
    image: Albums[16].cover,
    artists: ['OPYI', 'Birat Bitz'],
    album: 'ICE BLUE',
    duration: '3:15',
  },
  {
    id: 3,
    albumId: 17,
    title: 'DESPERTAR',
    image: Albums[16].cover,
    artists: ['OPYI', 'Birat Bitz'],
    album: 'ICE BLUE',
    duration: '3:31',
  },
  {
    id: 4,
    albumId: 17,
    title: 'VICE',
    image: Albums[16].cover,
    artists: ['OPYI', 'Birat Bitz'],
    album: 'ICE BLUE',
    duration: '3:05',
  },
  {
    id: 5,
    albumId: 17,
    title: 'GYAL',
    image: Albums[16].cover,
    artists: ['OPYI', 'Birat Bitz'],
    album: 'ICE BLUE',
    duration: '2:54',
  },
  {
    id: 6,
    albumId: 17,
    title: 'BAHIA',
    image: Albums[16].cover,
    artists: ['OPYI', 'Birat Bitz'],
    album: 'ICE BLUE',
    duration: '3:01',
  },
  {
    id: 7,
    albumId: 17,
    title: 'FENDI BAG',
    image: Albums[16].cover,
    artists: ['OPYI', 'Birat Bitz'],
    album: 'ICE BLUE',
    duration: '2:59',
  },
  

  /*-------Proof disc 1--------- */
  {
    id: 1,
    albumId: 18,
    title: 'Born Singer',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:58',
  },
  {
    id: 2,
    albumId: 18,
    title: 'No More Dream',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:42',
  },
  {
    id: 3,
    albumId: 18,
    title: 'N.O',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:29',
  },
  {
    id: 4,
    albumId: 18,
    title: 'Boy In Luv',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:51',
  },
  {
    id: 5,
    albumId: 18,
    title: 'Danger',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '4:05',
  },
  {
    id: 6,
    albumId: 18,
    title: 'I NEED U',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:30',
  },
  {
    id: 7,
    albumId: 18,
    title: 'RUN',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:56',
  },
  {
    id: 8,
    albumId: 18,
    title: 'Burning Up (FIRE)',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:23',
  },
  {
    id: 9,
    albumId: 18,
    title: 'Blood Sweat & Tears',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:37',
  },
  {
    id: 10,
    albumId: 18,
    title: 'Spring Day',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '4:34',
  },
  {
    id: 11,
    albumId: 18,
    title: 'DNA',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:43',
  },
  {
    id: 12,
    albumId: 18,
    title: 'fake love',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '4:02',
  },
  {
    id: 13,
    albumId: 18,
    title: 'IDOL',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:42',
  },
  {
    id: 14,
    albumId: 18,
    title: 'Boy With Luv (Feat. Hallsey)',
    image: Albums[17].cover,
    artists: ['BTS', 'Halsey'],
    album: 'Proof',
    duration: '4:55',
  },
  {
    id: 15,
    albumId: 18,
    title: 'ON',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '4:06',
  },
  {
    id: 16,
    albumId: 18,
    title: 'Dynamite',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:19',
  },
  {
    id: 17,
    albumId: 18,
    title: 'Life Goes On',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:28',
  },
  {
    id: 18,
    albumId: 18,
    title: 'Butter',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '2:44',
  },
  {
    id: 19,
    albumId: 18,
    title: 'Yet To Come',
    image: Albums[17].cover,
    artists: ['BTS'],
    album: 'Proof',
    duration: '3:13',
  },

  /*-------eternal sunshine--------- */
  {
    id: 1,
    albumId: 19,
    title: 'intro (end of the world)',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '1:32',
  },
  {
    id: 2,
    albumId: 19,
    title: 'bye',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '2:44',
  },
  {
    id: 3,
    albumId: 19,
    title: 'don\'t wanna break up again',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '2:54',
  },
  {
    id: 4,
    albumId: 19,
    title: 'Saturn Returns Interlude',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '0:42',
  },
  {
    id: 5,
    albumId: 19,
    title: 'eternal sunshine',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '3:30',
  },
  {
    id: 6,
    albumId: 19,
    title: 'supernatural',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '2:43',
  },
  {
    id: 7,
    albumId: 19,
    title: 'true story',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '2:43',
  },
  {
    id: 8,
    albumId: 19,
    title: 'the boy is mine',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '2:16',
  },
  {
    id: 9,
    albumId: 19,
    title: 'yes, and?',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '3:34',
  },
  {
    id: 10,
    albumId: 19,
    title: 'we can\'t be friends (wait for your love)',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '3:48',
  },
  {
    id: 11,
    albumId: 19,
    title: 'i wish i hated you',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '2:33',
  },
  {
    id: 12,
    albumId: 19,
    title: 'imperfect for you',
    image: Albums[18].cover,
    artists: ['Ariana Grande'],
    album: 'eternal sunshine',
    duration: '3:02',
  },
  {
    id: 13,
    albumId: 19,
    title: 'ordinary things (feat. Nonna)',
    image: Albums[18].cover,
    artists: ['Ariana Grande', 'Nonna'],
    album: 'eternal sunshine',
    duration: '2:48',
  },
      
      
      
]

